### ISSUE TITLE
Possibility to create shortcuts with ID

### ISSUE THREAD

**Issue by timofo** [FriendsOfTYPO3/interest#121]
At the moment it is only possible to create shortcuts with remote_id's with TYPO3 12 and interest 2.1.2.
Is there also a possibility to add an ID as a “records” value to shortcuts?

**Comment by mabolek** [comment]
Hi @timofo!

If I understand you correctly, you would like to reference a real UID instead of a remote ID, so instead of `'records':['myRemoteId']` in your data, you would use `'records':[123]`.

This is not currently possible, because the interest extension will assume that everything you put into a relation field is a remote ID. It's also hard to implement a way where it can graciously switch between the two. The interest extension is built to allow you to know *nothing* about the TYPO3 side of things when pushing data.

However, you could implement an event handler that automatically creates a remote ID in the mapping table if the remote id encountered is in a specific format. Let's say the remote ID is `pages:123`, then the event handler could create a mapping entry from `pages:123` to UID `123` in the `pages` table. This could be done either when the page is created (or by some script at any time) or at runtime as needed. Check out the [Changing and Extending](https://docs.typo3.org/p/pixelant/interest/main/en-us/Implementing/Extending/Index.html) chapter of the documentation.

Let me know if that is helpful.

**Comment by timofo** [comment]
Thank you for the info. :-)
I will try it when I get the chance.
